### ISSUE TITLE
Allow serializing more complex enums

### ISSUE THREAD

**Issue by alexschrod** [dtolnay/serde-repr#15] opened 2022-03-02 05:08 UTC
I have an enum I'd like to serialize that looks like this:
```rust
#[derive(Debug, Deserialize, Serialize)]
#[serde(tag = "type")]
#[repr(u8)]
pub(crate) enum CustomViewOptionType {
    ByMonth { year: u16, month: u8 },
    ByYear { year: u16 },
    Range { start: NaiveDate, end: NaiveDate },
    Last30Days,
    All,
}
```
Running this through `serde_json`, you get something like
```json
{ "type": "ByMonth", "year": 2018, "month": 6 }
```
What I want to end up with is instead
```json
{ "type": 0, "year": 2018, "month": 6 }
```
Despite the `#[repr(u8)]`, which the Rust compiler happily accepts for my non-unit enum, `serde-repr` tells me
```
error: must be a unit variant
   --> src\models.rs:244:5
    |
244 |     ByMonth { year: u16, month: u8 },
    |     ^^^^^^^
```
but I don't want a unit variant. I just want the enum tag serialized as a number rather than as text. What can I do?

**Comment by dtolnay** [comment] 2023-10-30 01:08
This is a duplicate of #6.

**Closed by dtolnay** 2023-10-30 01:08 UTC
